const MAIN_COLOR = '#87CEEB';// '#6DA2FF';
const BACKGROUND_COLOR = '#F5F5F5';
const LIGHT_COLOR = '#f5f5f5';
const NEUTRAL_COLOR = '#A09DAC';
const DARK_COLOR = '#3C3C43';

const COLORS = {
	MAIN_COLOR,
	BACKGROUND_COLOR,
	LIGHT_COLOR,
	NEUTRAL_COLOR,
	DARK_COLOR
};

export default COLORS;
