const MAIN_COLOR = '#6DA2FF';
const BACKGROUND_COLOR = '#F5F5F5';
const LIGHT_COLOR = '#f5f5f5';
const NEUTRAL_COLOR = '#A09DAC';

const COLORS = {
	MAIN_COLOR,
	BACKGROUND_COLOR,
	LIGHT_COLOR,
	NEUTRAL_COLOR,
};

export default COLORS;
