const MAIN_COLOR = '#6DA2FF'
const BACKGROUND_COLOR = '#F5F5F5'
const LIGHT_COLOR = '#FAFAFA'
const NEUTRAL_COLOR = '#A09DAC'

export {
    MAIN_COLOR,
    BACKGROUND_COLOR,
    LIGHT_COLOR,
    NEUTRAL_COLOR,
}